[package]
name = "alot"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.65.0"
repository = "https://github.com/khonsulabs/alot"
readme = "./README.md"

[dependencies]
