name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: hecrj/setup-rust-action@v1

      - name: Run clippy (no features)
        run: |
          cargo clippy --no-default-features

      - name: Run clippy (all features)
        run: |
          cargo clippy --features std,serde,integer128

      - name: Run clippy (std,serde)
        run: |
          cargo clippy --features std,serde

      - name: Run clippy (serde)
        run: |
          cargo clippy --no-default-features --features serde

      - name: Run clippy (std)
        run: |
          cargo clippy --no-default-features --features std

      - name: Run clippy (integer128)
        run: |
          cargo clippy --no-default-features --features integer128

      - name: Run unit tests
        run: |
          cargo test --all-targets --features std,serde

      - name: Run unit tests (integer128)
        run: |
          cargo test --all-targets --features std,serde,integer128

  build-msrv:
    name: Test on MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: 1.65
      - name: Run unit tests
        run: cargo test --all-targets --features std,serde,integer128

  build-nostd:
    name: Build on no_std target (thumbv7em-none-eabi)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: thumbv7em-none-eabi
      - run: cargo build --target thumbv7em-none-eabi --lib --release --no-default-features

  build-serde:
    name: Build on no_std target (thumbv7em-none-eabi)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: thumbv7em-none-eabi
      - run: cargo build --target thumbv7em-none-eabi --lib --release --no-default-features --features serde,integer128
