name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: hecrj/setup-rust-action@v1

      - name: Run clippy
        run: |
          cargo clippy

      - name: Run unit tests
        run: |
          cargo test --all-targets --all-features


  build-msrv:
    name: Test on MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: 1.65
      - name: Run unit tests
        run: cargo test --all-targets --all-features

  build-nostd:
    name: Build on no_std target (thumbv7em-none-eabi)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: thumbv7em-none-eabi
      - run: cargo build --target thumbv7em-none-eabi --lib --release
